name: Build YouTube Wrapper

on:
  workflow_dispatch: # Позволяет запускать сборку кнопкой

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Theos
        run: |
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos)"
          echo "THEOS=/Users/runner/theos" >> $GITHUB_ENV

      - name: Setup SDK
        run: |
          curl -LO https://github.com/theos/sdks/raw/master/iPhoneOS10.3.sdk.tar.xz
          tar -xJf iPhoneOS10.3.sdk.tar.xz -C $THEOS/sdks/

      - name: Build Package
        run: |
          export THEOS=$THEOS
          make package FINALPACKAGE=1
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: YouTubeWrapper-DEB
          path: packages/*.deb
